/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.Frame;
import java.awt.event.ItemEvent;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author alu20909379x
 */
public class Cover extends javax.swing.JDialog {

    public boolean isSelected;

    /**
     * Creates new form Cover
     */
    public Cover(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        imagePanel1 = new snake.ImagePanel();
        jBtnPlay = new javax.swing.JButton();
        jRadioButtonModeNormal = new javax.swing.JRadioButton();
        jRadioButtonModeHard = new javax.swing.JRadioButton();
        jCheckBoxWithoutWalls = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jBtnPlay.setBackground(new java.awt.Color(255, 51, 51));
        jBtnPlay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnPlay.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPlay.setText("PLAY");
        jBtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlayActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonModeNormal);
        jRadioButtonModeNormal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRadioButtonModeNormal.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButtonModeNormal.setText("Mode Normal");
        jRadioButtonModeNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonModeNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonModeHard);
        jRadioButtonModeHard.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRadioButtonModeHard.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButtonModeHard.setText("Mode Hard");
        jRadioButtonModeHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonModeHardActionPerformed(evt);
            }
        });

        jCheckBoxWithoutWalls.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxWithoutWalls.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBoxWithoutWalls.setText("Without Walls");
        jCheckBoxWithoutWalls.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxWithoutWallsItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 51, 51));
        jRadioButton1.setText("Personalized");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jBtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(14, 14, 14))
                    .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                            .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonModeHard)
                                .addComponent(jRadioButtonModeNormal))
                            .addGap(10, 10, 10))
                        .addComponent(jCheckBoxWithoutWalls, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxWithoutWalls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonModeNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonModeHard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1))
                    .addComponent(jBtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel1.add(imagePanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlayActionPerformed
        if (isSelected) {
           
            dispose();
        }

    }//GEN-LAST:event_jBtnPlayActionPerformed

    private void jRadioButtonModeNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonModeNormalActionPerformed
        ConfigSingleton.getInstance().setModeNormal(true);
        isSelected = true;
        ConfigSingleton.getInstance().setModeHard(false);
        ConfigSingleton.getInstance().setPersonalized(false);
    }//GEN-LAST:event_jRadioButtonModeNormalActionPerformed

    private void jRadioButtonModeHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonModeHardActionPerformed
        ConfigSingleton.getInstance().setModeHard(true);
        isSelected = true;
        ConfigSingleton.getInstance().setModeNormal(false);
        ConfigSingleton.getInstance().setPersonalized(false);
    }//GEN-LAST:event_jRadioButtonModeHardActionPerformed

    private void jCheckBoxWithoutWallsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxWithoutWallsItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ConfigSingleton.getInstance().setWithoutWalls(true);
        } else {
            ConfigSingleton.getInstance().setWithoutWalls(false);
        }
    }//GEN-LAST:event_jCheckBoxWithoutWallsItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ConfigSingleton.getInstance().setPersonalized(true);
        isSelected = true;
        ConfigSingleton.getInstance().setModeHard(false);
        ConfigSingleton.getInstance().setModeNormal(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cover dialog = new Cover(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private snake.ImagePanel imagePanel1;
    private javax.swing.JButton jBtnPlay;
    private javax.swing.JCheckBox jCheckBoxWithoutWalls;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonModeHard;
    private javax.swing.JRadioButton jRadioButtonModeNormal;
    // End of variables declaration//GEN-END:variables
}
