/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.event.ItemEvent;

/**
 *
 * @author alu20909379x
 */
public class Personalized extends javax.swing.JDialog {

    /**
     * Creates new form Personalized
     */
    public Personalized(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumRows = new javax.swing.JLabel();
        jLabelNumCols = new javax.swing.JLabel();
        jLabelSpeed = new javax.swing.JLabel();
        jCheckBoxWithoutWalls = new javax.swing.JCheckBox();
        jTextFieldNumRows = new javax.swing.JTextField();
        jTextFieldNumCols = new javax.swing.JTextField();
        jTextFieldSpeed = new javax.swing.JTextField();
        jBtnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jLabelNumRows.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNumRows.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNumRows.setText("Number of rows:");

        jLabelNumCols.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNumCols.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNumCols.setText("Number of Cols :");

        jLabelSpeed.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSpeed.setForeground(new java.awt.Color(255, 51, 51));
        jLabelSpeed.setText("Speed:");

        jCheckBoxWithoutWalls.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxWithoutWalls.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBoxWithoutWalls.setText("Without Walls");
        jCheckBoxWithoutWalls.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxWithoutWallsItemStateChanged(evt);
            }
        });

        jTextFieldNumRows.setText("25");

        jTextFieldNumCols.setText("25");

        jTextFieldSpeed.setText("200");

        jBtnPlay.setBackground(new java.awt.Color(255, 51, 51));
        jBtnPlay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnPlay.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPlay.setText("PLAY");
        jBtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNumCols, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNumRows, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumRows)
                            .addComponent(jTextFieldNumCols)
                            .addComponent(jTextFieldSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxWithoutWalls))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumRows, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumRows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumCols, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumCols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxWithoutWalls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jBtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxWithoutWallsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxWithoutWallsItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ConfigSingleton.getInstance().setWithoutWalls(true);
        } else {
            ConfigSingleton.getInstance().setWithoutWalls(false);
        }
    }//GEN-LAST:event_jCheckBoxWithoutWallsItemStateChanged

    private void jBtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlayActionPerformed
        ConfigSingleton.getInstance().setNum_rows(Integer.parseInt(jTextFieldNumRows.getText()));
        ConfigSingleton.getInstance().setNum_cols(Integer.parseInt(jTextFieldNumCols.getText()));
        ConfigSingleton.getInstance().setDeltaTime(Integer.parseInt(jTextFieldSpeed.getText()));
        

        dispose();

    }//GEN-LAST:event_jBtnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalized.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalized.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalized.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalized.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Personalized dialog = new Personalized(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPlay;
    private javax.swing.JCheckBox jCheckBoxWithoutWalls;
    private javax.swing.JLabel jLabelNumCols;
    private javax.swing.JLabel jLabelNumRows;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JTextField jTextFieldNumCols;
    private javax.swing.JTextField jTextFieldNumRows;
    private javax.swing.JTextField jTextFieldSpeed;
    // End of variables declaration//GEN-END:variables
}
